name: "FibBot"
description: "Extracts numbers from PRs and computes Fibonacci sequences"
inputs:
  enable_fib:
    description: "Enable Fibonacci calculation"
    required: true
    default: "true"
  max_threshold:
    description: "Maximum Fibonacci number limit"
    required: false
    default: "18"
outputs:
  input:
    description: "Print output to logs"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.enable_fib}}
    - ${{ inputs.max_threshold}}
