name: "FibBot"
description: "Extracts numbers from PRs and computes Fibonacci sequences"
env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
inputs:
  enable_fib:
    description: "Enable Fibonacci calculation (true or false)"
    required: true
    default: "true"
  max_threshold:
    description: "Maximum Fibonacci number limit (integer)"
    required: true
    default: "100"
outputs:
  input:
    description: "Print output to logs"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.enable_fib }}
    - ${{ inputs.max_threshold }}
    - ${{ secrets.GITHUB_TOKEN }} 
    - ${{ github.event.pull_request.number }}
    - ${{ github.actor }}
    - ${{ github.repository }}
