name: Rust Hello World

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run Rust code
        uses: ./
        with:
          enable_fib: false
          max_threshold: '50'