name: Rust Hello World

on:
  push:
    branches:
      - main
<<<<<<< HEAD
  pull_request:
    branches:
      - main
          
=======
>>>>>>> 736760607cad86ecbafb65e4e3e24cc34a1b3522

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run Rust code
        id: input
        uses: ./
        with:
          enable_fib: true
          max_threshold: 50
